//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QlBantrasua.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sanpham()
        {
            this.Chitietdonhang = new HashSet<Chitietdonhang>();
        }
    
        public int Masp { get; set; }
        public string Tensp { get; set; }
        public Nullable<decimal> Giatien { get; set; }
        public Nullable<int> Soluong { get; set; }
        public string Mota { get; set; }
        public string Anhbia { get; set; }
        public Nullable<int> Maloai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietdonhang> Chitietdonhang { get; set; }
        public virtual Loai Loai { get; set; }
    }
}
